In [30]:
import numpy as np

In [31]:
a=np.array([1,2,3])
b=np.array([6,7,8])
print(a)
print(b)

[1 2 3]
[6 7 8]


In [32]:
type(a)

numpy.ndarray

### BASIC OPERATION OF ARRAY

In [33]:
print(a+b)
print(a-b)
print(a*b)

[ 7  9 11]
[-5 -5 -5]
[ 6 14 24]


In [34]:
#creating a 2D array

arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [35]:
#creating 3D array

arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [36]:
print(arr.shape) #shape of the array

(2, 2, 3)


In [37]:
print(arr.ndim) #number of dimenison

3


In [38]:
print(arr.dtype)

int64


In [39]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.arange(-10,0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [41]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [42]:
np.random.randint(10,30,size=(3,3))

array([[13, 25, 23],
       [29, 20, 16],
       [21, 28, 23]], dtype=int32)

In [43]:
x=np.array([[7,2,3],[2,5,2],[3,5,1]])
y=np.array([[1,8,3],[4,5,6],[2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [4 5 6]
 [2 5 3]]


In [44]:
print(x+y)
print(x-y)
print(x*y)

[[ 8 10  6]
 [ 6 10  8]
 [ 5 10  4]]
[[ 6 -6  0]
 [-2  0 -4]
 [ 1  0 -2]]
[[ 7 16  9]
 [ 8 25 12]
 [ 6 25  3]]


In [45]:
#matrix multiplication
print(x@y)

[[21 81 42]
 [26 51 42]
 [25 54 42]]


In [46]:
print(x.dot(y))
np.dot(x,y)

[[21 81 42]
 [26 51 42]
 [25 54 42]]


array([[21, 81, 42],
       [26, 51, 42],
       [25, 54, 42]])

In [47]:
x.prod()

np.int64(12600)

In [48]:
x.mean()  #mean of all the element in the array

np.float64(3.3333333333333335)

In [49]:
round(x.mean()) #rounding the mean value

3

In [50]:
x.mean(axis=0) #mean along the first axis(column)

array([4., 4., 2.])

In [51]:
x.mean(axis=1)  #mean along the second axis(row)

array([4., 3., 3.])

In [52]:
print(x.sum()) #sum of all the element in the array
print(x.var())  #variance of all the element in the array
print(x.std())  #standard deviation of all the element in the array

30
3.3333333333333335
1.8257418583505538


In [53]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50))  #median
print(np.percentile(a,25))
print(np.percentile(a,75))  #interquartile range

5.0
3.0
7.0


In [54]:
b=np.random.randint(11,100,(4,4))
print(b)

[[81 74 11 12]
 [65 92 91 84]
 [83 34 92 86]
 [79 85 65 50]]


In [55]:
print(b.reshape(2,8))

[[81 74 11 12 65 92 91 84]
 [83 34 92 86 79 85 65 50]]


In [56]:
print(b.reshape(8,2))

[[81 74]
 [11 12]
 [65 92]
 [91 84]
 [83 34]
 [92 86]
 [79 85]
 [65 50]]


In [57]:
print(b)

[[81 74 11 12]
 [65 92 91 84]
 [83 34 92 86]
 [79 85 65 50]]


In [58]:
print(b[0]) #accessing first row

[81 74 11 12]


In [59]:
print(b[1]) #accessing the second row

[65 92 91 84]


In [60]:
print(b[0,1]) #accessing the first row and second column

74


In [61]:
print(b[-1])

[79 85 65 50]


In [62]:
print(b[:3])

[[81 74 11 12]
 [65 92 91 84]
 [83 34 92 86]]


In [63]:
print(b[3:])

[[79 85 65 50]]
